name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      nombres: "Marco Oswaldo"
      apellidos: "Tello Sánchez"
      edad: "21"

    steps:
      - uses: actions/checkout@v4
      - name: presentación
        run: |
          echo "Nombres: $nombres"
          echo "Apellidos: $apellidos"
          echo "Edad: $edad"

      - name: datos generales
        run: echo "carrera de ingeniería de sistemas"

      - name: variables de entorno secretas
        env:
          user: ${{ secrets.user }}
          password: ${{ secrets.password }}
        run: |
          echo "user: $user"
          echo "password: $password"

      - name: variables abiertas
        run: |
          echo "Versión del proyecto: ${{ vars.version_proyecto }}"
